### ISSUE TITLE
unable to generate solution for Xcode

### ISSUE THREAD

**Issue by ikryukov** [premake/premake-xcode#20]
Hi, I downloaded the latest source and build it on Mac. But now I'm getting this error message:
premake-core/modules/xcode/xcode_common.lua:317: bad argument #1 to 'pairs' (table expected, got nil)
Could anyone provide premake5 that works on MacOS 10.10.
Thanks, Ilya.

Here is my premake lua file: 

-- fluid.lua
workspace "Fluid"
   configurations { "Debug", "Release" }
   location "build/Fluid"
   architecture "x86_64"

project "Fluid"
   kind "ConsoleApp"
   language "C++"
   targetdir "../bin/%{cfg.buildcfg}"

   files { "../src/*_.h", "../src/_.cpp" }

   includedirs { "../3rdparty/GLFW/include"
   , "../3rdparty/GLEW/include"
   , "../3rdparty/glm/include"
   , "../3rdparty/boost/include" }

   libdirs { "../3rdparty/GLFW/lib"
   , "../3rdparty/GLEW/lib"
   , "../3rdparty/boost/lib" }

   links { "glfw3", "glew32", "glu32", "opengl32" }

   filter "configurations:Debug"
      defines { "DEBUG" }
      flags { "Symbols" }

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"

**Comment by thejustinwalsh** [comment]
Not sure if it matters but I use the `solution` function in place of where you are using `workspace`.

**Comment by ikryukov** [comment]
@thejustinwalsh I got the same message with solution instead of workspace keyword.

**Comment by samsinsane** [comment]
This was fixed in #19 but the submodule reference in premake-core is behind, I'll update these. I'll resolve this issue as you've created an issue over in premake-core too. Thanks for pointing this out!

Also, `solution` has been replaced by `workspace`, I'm not sure if the plan is to keep both, but I'd recommend using `workspace` as it will definitely be supported going forward.

**Comment by ikryukov** [comment]
@samsinsane Thanks for response!
